  
dist: focal

language: c

compiler:
    - gcc

addons:
    apt:
        update: true
        packages:
            - build-essential
            - cmake
            - pkgconf
            - wget
            - ca-certificates
            - udev
            - gettext
            - python3
            - python3-pip
            - python3-setuptools
            - python3-wheel
            - ninja-build              

before_install:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu
    - sudo pip3 install --system meson
    - bash <(curl -s https://raw.githubusercontent.com/falk-werner/install_deps/main/install_deps.sh) -s

before_script:
    - mkdir build
    - cd build
    - make

script:
    - ./alltests
