#ifndef RPC_STATUS_H
#define RPC_STATUS_H

#define RPC_GOOD 0
#define RPC_BAD -1

#define RPC_BAD_INVALID_RESPONSE_METHOD_ID -2

#define RPC_BAD_CONNECTION_READ_ERROR -3
#define RPC_BAD_CONNECTION_WRITE_ERROR -4
#define RPC_BAD_CONNECTION_CLOSED -5
#define RPC_BAD_MAX_MESSAGE_SIZE_EXCEEDED -6

#define RPC_BAD_UNKNOWN_SERIALIZER    -7
#define RPC_BAD_UNKNOWN_DESERIALIZER   -8

#define RPC_BAD_DESERIALIZE_FAILED -9

#endif
