name: 'build'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v3
      
      - name: Install APT dependencies
        run: sudo apt install build-essential cmake pkgconf wget ca-certificates udev gettext python3 python3-pip python3-setuptools python3-wheel ninja-build
      
      - name: Install meson
        run: sudo pip3 install --system meson
      
      - name: Install dependencies
        run: bash <(curl -s https://raw.githubusercontent.com/falk-werner/install_deps/main/install_deps.sh) -s

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./alltests
